services:
    frontend:
        image: node:18-bullseye
        working_dir: /app
        volumes:
            - ./frontend:/app
        command: >
            sh -c "npm install && npm run prebuild && npm run dev -- --host"
        ports:
            - "5173:5173"

    mqtt:
        image: eclipse-mosquitto:2.0
        ports:
            - "1883:1883"
        volumes:
            - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf

    dynamodb:
      image: amazon/dynamodb-local
      command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data -port 8000"
      volumes:
        - ./dynamodb/data:/home/dynamodblocal/data
      ports:
        - "8000:8000"
  
    backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      volumes:
        - ./backend:/app
      env_file:
        - ./backend/.env
      ports:
        - "8001:8001"
